targets:
  $default:
    builders:
      gql_build|schema_builder:
        enabled: true
        options:
          schema: graphql_test_flutter|lib/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'
      gql_build|ast_builder:
        enabled: true
      gql_build|data_builder:
        enabled: true
        options:
          schema: graphql_test_flutter|lib/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'
      gql_build|var_builder:
        enabled: true
        options:
          schema: graphql_test_flutter|lib/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'
      gql_build|serializer_builder:
        enabled: true
        options:
          schema: graphql_test_flutter|lib/schema.graphql
          custom_serializers:
            - import: 'package:graphql_test_flutter/upload_serializer.dart'
              name: UploadSerializer

      ferry_generator|req_builder:
        enabled: true
        options:
          schema: graphql_test_flutter|lib/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'